name = "firecrawl-mcp"
main = "index.js"
compatibility_date = "2024-12-01"

[env.production]
name = "firecrawl-mcp-prod"

[vars]
# Add your Firecrawl API key as a secret
# wrangler secret put FIRECRAWL_API_KEY